-- Cavi ERP — hash-chained audit log (W7 / FR7)
-- Makes event_log tamper-evident: each new row carries chain_hash =
-- sha256(previous chain_hash + canonical(event)), computed by the event store
-- under a transaction-scoped advisory lock (see shared/events.py and
-- shared/audit.py). Editing, deleting, or reordering any chained row breaks
-- every hash after it; scripts/audit_export.py exports and verifies.
--
-- The chain era starts HERE: rows recorded before this migration keep
-- chain_hash NULL (the chain does not pretend to notarize history that
-- predates it). seq gives the chain its total order.
-- Idempotent: ADD COLUMN IF NOT EXISTS, safe to re-run.

ALTER TABLE event_log ADD COLUMN IF NOT EXISTS seq BIGINT
    GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE event_log ADD COLUMN IF NOT EXISTS chain_hash TEXT;

-- The chain is read tip-first at every append; keep that lookup indexed.
CREATE UNIQUE INDEX IF NOT EXISTS idx_event_log_seq ON event_log (seq);
CREATE INDEX IF NOT EXISTS idx_event_log_chained
    ON event_log (seq DESC) WHERE chain_hash IS NOT NULL;
